### ISSUE TITLE
Unexpected keyword argument when using keywords with '__'

### ISSUE THREAD

**Issue by vdanen** [RedHatProductSecurity/osidb-bindings#17]
When using osidb-bindings and querying "params={'reported_dt__date__lte': "2022-07-26", 'component': "kernel", "include_fields": "cve_id,title,impact,type"}" I get the following error:

```
Traceback (most recent call last):
  File "/Users/redhat/srt/vdanen/scripts/osidb/osidb-client.py", line 52, in <module>
    resp = session.flaws.retrieve_list(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/osidb_bindings/session.py", line 279, in retrieve_list
    sync_fn(*args, client=self.client(), **kwargs), *args, **kwargs
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sync() got an unexpected keyword argument 'reported_dt__date__lte'
```

But using the same with curl directly works:

```
$ curl 'https://HOST/osidb/api/v1/flaws?reported_dt__date__gte=2022-07-26&include_fields=cve_id,reported_dt' | jq
```

**Comment by xquery** [comment]
unsure - the binding might expect a datetime value in python ... you might try that ...

**Comment by JakubFrejlach** [comment]
@xquery is right about the need of the python datetime value, currently the string is not supported (it is definitely doable, it just wasn't requested yet), however the problem here is something else. Package `openapi-python-client` handles double underscore params in a weird way and internally it expects `reported_dt_date_lte` instead of `reported_dt__date__lte` and it only uses the double underscores when making the request.

We've already had to workaround this in griffon too (https://github.com/RedHatProductSecurity/griffon/pull/181/commits/a46258b3f5df0e435241e0585a864784602320dc)

We've never had any double underscore query params in OSIDB until now so it wasn't an issue before. Current workaround is to use single underscores instead of double underscores but I will try to tamper with the bindings templates to force the double underscores names.
